spring:
  #  datasource:
  #    url: jdbc:mysql://localhost:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  #    username: root
  #    password: root
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: csmall-for-jsd-stock
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        #是否当前服务实例,是临时实例 true(临时实例) false(永久实例)
        ephemeral: true
        #ip地址,当前客户端进程所在服务器的ip地址,如果默认的,就是springboot自动读取的服务器ip
        #ip地址
        ip: 127.0.0.1
        #定义命名空间,选择不同环境 dev,配置命名空间id
        namespace: 0ca3e672-a485-4819-b51b-c067f58aef67
        #定义这个实例所属的分组,一般用版本相关内容的值去区分
        group: 0.0.1-SNAPSHOT
        #心跳检测间隔时间
        heart-beat-interval: 5
        #超时心跳时间删除
        ip-delete-timeout: 15
    sentinel:
      datasource:
        nacosDatasource:
          nacos-degrade-datasource:
            nacos:
              #nacos配置地址
              server-addr: localhost:8848
              #namespace从哪个命名空间 启动nacos获取命名空间id
              namespace: 0ca3e672-a485-4819-b51b-c067f58aef67
              #分组
              group-id: 0.0.1-SNAPSHOT
              #读取远程文件名称 熔断文件
              data-id: degrade.rules
              #规则有很多中 限流,熔断,有系统保护规则 指定当前flow.rules里配置的规则种类
              rule-type: degrade
              #读取文件的数据类型 json
              data-type: json
              #需要指定在nacos数据源中
              username: nacos
              password: nacos
dubbo:
  application:
    # 所有微服务中application.name 使用${}引用一下我们配置过的这个名字
    name: ${spring.application.name}
  #dubbo协议
  protocol:
    #dubbo使用nacos作为注册中心 注册的协议信息
    #-1表示从20880端口开始,选择第一个空端口
    port: -1
    name: dubbo
  #配置注册中心属性
  registry:
    #告诉dubbo注册中心类型和地址
    address: nacos://localhost:8848
    #分组 和nacos之前分组完全一样的.
    group: 0.0.1-SNAPSHOT
    #命名空间 dev 这个属性没有提示
    parameters:
      registry-type: nacos
      namespace: 0ca3e672-a485-4819-b51b-c067f58aef67
    #关闭在nacos中dubbo提供的一些默认的配置注册信息,如果不关闭,随着dubbo
    #客户端运行nacos配置中心列表中会出现大量重复
    use-as-config-center: false
    use-as-metadata-center: false
  consumer:
    #关闭consumer的检查功能,如果不关闭,在consumer一旦发现服务注册中心
    #没有调用的服务,就会报错
    check: false
tarena:
  user:
    #开启自动配置的条件
    enable: true
    #属性注入
    name: 王翠花
