spring:
#  #数据源
#  datasource:
#    url: jdbc:mysql://localhost:3306/csmall_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver

  #nacos交互的相关属性
  application:
    #应用名称,spring框架里搭建微服务的时候,称为服务名称
    #只要是同一个功能的系统,都是同一个服务名称
    name: csmall-for-jsd-cart
  #配置nacos相关的属性
  cloud:
    nacos:
      discovery:
        #提供当前nacos客户端可以通信访问的服务端地址
        server-addr: localhost:8848
        ip: 10.1.6.76
        namespace: 0ca3e672-a485-4819-b51b-c067f58aef67
        group: 0.0.1-SNAPSHOT
        heart-beat-interval: 5