server:
  port: 20010
#公共配置
mybatis:
  configuration:
    cache-enabled: false   # 不启用mybatis缓存
    map-underscore-to-camel-case: true # 映射支持驼峰命名法
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 将运行的sql输出到控制台
spring:
  profiles:
    active: local

logging:
  level:
    cn.tedu.csmall: debug

#rocketmq相关属性
rocketmq:
  #连接nameserver
  name-server: localhost:9876
  #默认的生产者和消费者分组 其中消费者组可以在使用注解监听队列时修改
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group
